<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class User extends BaseUser
{
	
	//const USER_SET_STATUS = 0;
	
	const INVALID_NEW_PASSWORD_STATUS = "-2";
	const INVALID_OLD_PASSWORD_STATUS = "-1";
	const SUCCESS = "200";

	public function setPassword($password) {
		
		return $this->_set('password', md5($password));
	}

	public function validatePassword($passwordToBeVerified) {
		if ($this->password == md5($passwordToBeVerified)) {

               return true;
		}
		return false;
	}
	
	public function validateEmail($emailToBeVerified) {
		if ($this->email == ($emailToBeVerified)) {
			return true;
		}
		return false;
	}
	

	public function addUser($params) {
		
		$this->firstName = BackEnd_Helper_viewHelper::stripSlashesFromString($params['firstName']);
		$this->email = BackEnd_Helper_viewHelper::stripSlashesFromString($params['email']);
		$this->lastName =BackEnd_Helper_viewHelper::stripSlashesFromString($params['lastName']);
		$this->password = BackEnd_Helper_viewHelper::stripSlashesFromString($params['password']);
		$this->ZipCode= BackEnd_Helper_viewHelper::stripSlashesFromString($params['ZipCode']);
		$this->roleId = $params['usertype'];
		
		//call doctrine save function 
		$this->save();
		return $this->id;
		}
	
	
	public static function checkDuplicateUser($email)
	{

		// $cnt  = Doctrine_Core::getTable("User")->findBy('email', $email)->count();
		$cnt  = Doctrine_Query::create()
		->from("User")->select()->where('email= ?', $email)->andWhere("deleted= 0")->fetchArray();
		// ->findBy('email', $email)->count();
		
		return count($cnt);
	}
	


	public function updateLoginTime($id){
		
		$user = Doctrine_Core::getTable("User")->find($id);
		if($user->currentLogIn=='0000-00-00 00:00:00'){
			$user->currentLogIn = date('Y-m-d H:i:s');
		}
		$user->lastLogIn = $user->currentLogIn;
		$user->currentLogIn = date('Y-m-d H:i:s');
		$user->save();
	}

	
	public function update($params,$imageName='') {
	   
		
		$this->firstName =BackEnd_Helper_viewHelper::stripSlashesFromString ($params['firstName']);
		$this->lastName =BackEnd_Helper_viewHelper::stripSlashesFromString ($params['lastName']);
		$this->phoneNumber= BackEnd_Helper_viewHelper::stripSlashesFromString($params['phoneNumber']);
		$this->Address= BackEnd_Helper_viewHelper::stripSlashesFromString($params['Address']);
		$this->ZipCode= BackEnd_Helper_viewHelper::stripSlashesFromString($params['ZipCode']);
		//$this->roleId= BackEnd_Helper_viewHelper::stripSlashesFromString($params['role']);
		
	
		
		
	    
		
		$this->save();
		
	
		// check user want to update password or not based upon old password
		if( strlen($params['oldPassword'])  > 7 )
		{
			// check user entered correct old password or not 
			if(self::validatePassword($params['oldPassword']))
			{
				if(strlen($params['confirmNewPassword'])  > 7)
				{
					
					// encrypt new passsword
					self::setPassword($params['confirmNewPassword']) ;
					
				} else {
					// send error code and message
					return array("status" => self::INVALID_NEW_PASSWORD_STATUS ,
							"message" => "Invalid new password" );					
				}
			} else
			{
				// send error code and message
				return array("status" => self::INVALID_OLD_PASSWORD_STATUS ,
						 "message" => "Old Password don't matched" );
			}
			
		}
		
		$this->save();
	
		// update session if profile is being updated
		if($this->id == Auth_StaffAdapter::getIdentity()->id)
		{
				new Zend_Auth_Result(Zend_Auth_Result::SUCCESS, $this);
		}
		



		
		return array("ret" => $this->id , "status" => self::SUCCESS, 
				"message" => "Record has been updated successfully");
	}		
		

	
	public static function getuserdetail($params) {
	
		$id = @$params['uId'];
		$data = Doctrine_Query::create()->select("u.*,pi.*")
		->from('User u')
		//->leftJoin("u.profileimage pi")
		->where('u.id=?',$id)
		->andWhere("u.id != 1")
		->andWhere("u.status = 1")
		->fetchArray();
	
		$result = @$data[0];
		return $result;
	}
	
  public static function getUserList($params){
  	//$role = $params['role'];
  	$srh = @$params['searchtext'];
  	
  	$data = Doctrine_Query::create()
  		->select()
  		->from("User u")
  		->where('u.deleted=0')
  		->andWhere('u.id!=1')
  		->andWhere('u.roleId!=1')
  		->andWhere('u.roleId!=2');
  		if($srh!='undefined'){
  		$data->andWhere("u.firstName LIKE ?", "$srh%");
  		}
  		$data->orderBy("u.id DESC");
    return Zend_Json::encode(
  			DataTable_Helper::generateDataTableResponse($data,
  					$params,
  					array("__identifier" => 'u.firstName','u.email','u.roleId','u.created_at','u.updated_at'),
  					array(),
  					array()
  					));
  }
  
  public static function searchKeyword($keyword) {
  	$status="null";
  	$data = Doctrine_Query::create()
  	->select('u.firstname as firstname')
  	->from("User u")
  	->where('u.deleted=0')
  	->andWhere("u.firstname LIKE ?", "$keyword%")
  	->andWhere('u.id!=1')
  	->andWhere("u.deleted=0")
  	->orderBy("u.firstname ASC")
  	->limit(5)->fetchArray();
  	return $data;
  }
  

 

  public static function getAllUserDetail(){
  	
  $data = Doctrine_Query::create()->select("u.firstName, u.lastName,u.phoneNumber,u.address,u.ZipCode")
  	->from('User u')
  //	->leftJoin("u.profileimage pi")
  	->where("u.deleted = 0")
  	->fetchArray();
  	return $data;
  }

  public static function changeStatus($params) {
  //echo "<pre>";
   //print_r($params); die;
  	$status = $params['status'] == 'offline' ? '1' : '0';
  	$q = Doctrine_Query::create()
					  	->update('User u')
					  	->set('u.status', $status)
					  	->where('u.id=?', $params['id'])
					  	->execute();
  	print_r($status); 
  //	echo Zend_Json::encode('1');
  
  }
  
 


/*****************************************Web services start by rkumar*******************************************/
  
 public function addendUser($params) {
  	

  	$currdate = date("Y-m-d", strtotime( "today" ));
  		
  	$this->email = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['email']);
  	if(isset($params['facebookId']) && @$params['facebookId'] != NULL){
  		$this->facebookId = BackEnd_Helper_viewHelper::stripSlashesFromString($params['facebookId']);
  	}
  	if(!isset($params['facebookId']) && @$params['facebookId'] == NULL){
  	$this->password = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['password']);
  	}
  	$this->ZipCode = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['ZipCode']);
  	$this->dob = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['birthDate']);
	$this->Gender = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['gender']);
	$this->DeviceToken = BackEnd_Helper_viewHelper::stripSlashesFromString(@$params['Token']);
	$this->roleId = 2; // This type for end user
  if(!isset($params['facebookId']) && @$params['facebookId'] == NULL){
  	
	$this->usertype = "S";
	  	}else{
	
	$this->usertype = "F";
	  	}
	$this->isLogin = "1";
	
	$this->downloadDate = $currdate;
	
	  	// call doctrine save function
	  	$this->save();
	  	$result = $this->id;
	  	return $result;
  }
  
	  	
  
 public function findUser($params) { // for login models
	  	 
	 	 	
	  	 
	  	$email = @$params['email'];
	  	$passwrd = @md5($params['passwrd']);
	  	$roleId = @$params['roleId'];
	  	$usertype = @$params['usertype'];
	  	
	  	$qry = Doctrine_Query::create()->select("u.firstName, u.lastName, u.email, u.roleId, u.notificationStatus,u.downloadStatus,u.downloadDate")
	  	->from('User u')
	  	->where('u.email='."'$email'")
	  	->andWhere('u.password='."'$passwrd'")
	 	->whereIn("u.roleId", $roleId)
	 	->andWhere('u.status='.true);
	 	if(isset($params['usertype']))
	 	{
	 		$qry->andWhere('u.usertype='."'$usertype'") ;
	 	
	 	}
	 	
	 //	echo $qry->getSqlQuery();
	 	
	  	$data = $qry->fetchArray();
	  	$result = @$data[0];
	 
	  	return $result;
	  }
	  
	  /*
	   * function to to get user by email to check payment status
	  * @author Ravneet
	  * Dated 10th dec,2013
	  */
	  public function checkPaymentStatus($params)
	  {
	  	$email = @$params['email'];
	  	$roleId = 2;
	  	$usertype = $params['usertype'];
	  
	  	$qry = Doctrine_Query::create()->select("u.downloadStatus,u.downloadDate")
	  	->from('User u')
	  	->where('u.email='."'$email'")
	  	->whereIn("u.roleId", $roleId)
	  	->andWhere('u.status='.true);
	  
	  	$qry->andWhere('u.usertype='."'$usertype'") ;
	  
	  	//	echo $qry->getSqlQuery();
	  	 
	  	$data = $qry->fetchArray();
	  	$data = $qry->fetchArray();
	  	$result = @$data[0];
	  	 
	  	return $result;
	  
	  }
	  
	  /*
	   * function to update subscription(unpaid to paid)
	  * @author Ravneet
	  * Dated 10th december,2013
	  */
	  public function updateSubscription( $email )
	  {
	  	$obj = Doctrine_Core::getTable ( 'User' )->findOneByemail ( $email );
	  	$obj->downloadStatus = "paid";
	  	$obj->save();
	  	return $obj->id;
	  }
	  
	  
	  /*
	   * Function to update  
	   * @author Er.kundal
	   * param: email
	   */
	  public static function forgotPass($eMail) {
	  	
	  	$result = Doctrine_Core::getTable ( 'User' )->findOneByemail ( $eMail );
	  	
	  	if ($result) {
	  			
	  		return array ('id' => $result ['id'], 'username' => $result ['firstName'] );
	  	} else {
	  		return false;
	  
	  	}
  }
  
  
  public static function getUsersLists(){
  	
 // In Bleeper get all users for push notifications 
  	$data = Doctrine_Query::create()
  	// ->distinct('u.DeviceToken')
  	->select("u.firstName, u.DeviceToken")
  	->from("User u")
  	->where('u.deleted=0')
  	->andWhere("u.roleId=2")
  	->andWhere('u.DeviceToken!= "NULL"')
	->andWhere("u.DeviceToken!= '(null)'")
  	->andWhere('u.DeviceToken!=""')
  	->groupBy('u.DeviceToken')
  	//->getSqlQuery();
	->fetchArray();
  	
  return $data;
  }
  
  
  // ws api for check token
  public function vailidate($params) {
  	 
  	  	 
  //	$token = @$params['Token'];
  	$email = @$params['email'];
  	
  	$data = Doctrine_Query::create()->select("u.*")
  	->from('User u')
  	//->where('u.DeviceToken='."'$token'")
  	->where('u.email='."'$email'")
  	->fetchArray();
  	
  	return @$data;
  }
  
  
  // ws api for check token
  public function vailidatefb($params) {
  
  	$fbId = @$params['facebookId'];
  	$email = @$params['email'];
  	 
  	/* $data = Doctrine_Query::create()->select("u.*")
  	->from('User u')
  	->where('u.facebookId='."'$fbId'")
  	->fetchArray(); */
  	
  	$data = Doctrine_Query::create()->select("u.*")
  	->from('User u')
  	->where('u.email='."'$email'")
  	->fetchArray();
  
  	return @$data;
  }
  
  
  // ws api for check token
  public static function getdetailbyemail($email) {
  
  	$data = Doctrine_Query::create()->select("u.*")
  	->from('User u')
  	->where('u.email='."'$email'")
  	->andWhereIn("u.usertype!='F'")
  	->fetchArray();
  
  	return @$data[0];
  }
  
  /*
   * function to get subscription status and subscription date of fb user
  * @author Ravneet
  * Dated 11th dec,2013
  *
  */
  public function getFbUser( $userId )
  {
  	$data = Doctrine_Query::create()
  	->select("u.downloadStatus,u.downloadDate")
  	->from('User u')
  	->where("u.id=".$userId)
  	->fetchArray();
  	return @$data[0];
  }
  
  // End Class  
}